ci(workflows): update gh-pages configuration

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -52,22 +52,16 @@ jobs:
             echo "No language files to update."
           else
             for i in $(seq 1 "$TOTAL_POSTS"); do
-              UPDATE_LANG_OUTPUT=$(python scripts/update_lang.py --max_files 1 --model mistral | grep "Total Markdown files to process:")
-              echo "$UPDATE_LANG_OUTPUT"
-              if [[ "$UPDATE_LANG_OUTPUT" == *'Total Markdown files to process: 0'* ]]; then
-                echo "No more language files to update."
-                break
-              else
-                git config user.name "github-actions[bot]"
-                git config user.email "github-actions[bot]@users.noreply.github.com"
-                git add _posts/**/*.md
-                git diff --cached --quiet || git commit -m "chore(lang): Update language files"
-                
-                git push || {
-                  echo "Push failed, attempting pull and merge"
-                  git pull --rebase
-                  git push
-                }
+              python scripts/update_lang.py --max_files 1 --model mistral
+              git config user.name "github-actions[bot]"
+              git config user.email "github-actions[bot]@users.noreply.github.com"
+              git add _posts/**/*.md
+              git diff --cached --quiet || git commit -m "chore(lang): Update language files"
+              git push || {
+                echo "Push failed, attempting pull and merge"
+                git pull --rebase
+                git push
+              }
               fi
             done
           fi
